# Generated by Django 6.0.6 on 2026-06-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_achievement_certificate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
