services:
  - type: web
    name: student-achievement-wallet-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed_demo && python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com,student-achievement-wallet-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://student-achievement-wallet-frontend.vercel.app,https://student-achievement-wall-git-79a2ea-professorelectrons-projects.vercel.app,https://student-achievement-wallet-frontend-8ojstnssd.vercel.app,http://localhost:5173
      - key: PYTHON_VERSION
        value: 3.13.5
