# Generated by Django 6.0.5 on 2026-06-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_achievement_token_id_achievement_tx_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='tx_hash',
            new_name='tx_Hash',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
