# Generated by Django 6.0.5 on 2026-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_tx_hash_achievement_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
